services:
  ingestor:
    build: .
    environment:
      POSTGRES_DB: my_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    depends_on:
      - db-server

  db-server:
    image: postgres:15
    environment:
      POSTGRES_DB: my_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  